### ISSUE TITLE
[ig/exploration] Exploration Group

### ISSUE THREAD

**Issue by plehegar** [w3c/strategy#451]
# Evaluation

A core part of our *Strategic* work is the evaluation of how proposed work serves the Web. In the "Evaluation" phase at the end of the funnel, we make the case whether work is ready to proceed to Chartering of a Recommendation-track deliverable. At that point, we need to identify:

* Will this work help to lead the web to its full potential?

https://w3c.github.io/charter-drafts/2024/ig-exploration.html

See also https://github.com/w3c/AB-memberonly/issues/207

* Is the work Rec-track ready?
  Not Rec-track
  
* Do we have the ecosystem of participants needed to make the work successful?

 unclear

  * users, developers, implementers; industry sectors
  * from that we can dig into
    * who specifically is involved? interested, opposed?
    * what tools and frameworks do they use?

Will it add value?
* something good for web users. what are the alternatives?

 continue as-is, with insufficient communication around the strategy work.

* have "horizontal" (a11y, i18n, security, privacy) issues been considered and identified?

 N/A

Will we be able to make it succeed?

unclear

* right participants interested. What does the ecosystem look like?

Special considerations?
* risk factors
* incentives
* openness, decentralization

## Procedural

[Issues](https://github.com/w3c/charter-drafts/issues?q=in%3Atitle%20ig%2Fexploration)

Next step is to start the AC Review

**Comment by plehegar** [comment]
AB supported moved forward with the proposal on April 11.

**Comment by plehegar** [comment]
We still need to find proposed chairs...

**Comment by plehegar** [comment]
Should invited experts gain Member-access for this Group ?

**Comment by himorin** [comment]
From i18n, we would like to ask adding a new item into a list in Scope, which mentions about horizontal activities, like

> Work with W3C Members and the W3C Team to evaluate the Web architecture, security, privacy, accessibility, and internationalization impacts of potential work areas. 

Also hope to check success criteria and coordination part near future.

**Comment by plehegar** [comment]
See also [issues](https://github.com/w3c/charter-drafts/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+exploration).

**Comment by simoneonofri** [comment]
No comments for security

**Comment by plehegar** [comment]
The Strategy team discussed this charter and remains skeptical about it:
1. We like the attempt at improving the technical strategy communication with the Members
1. However, it's not clear to us that this IG is going to be successful. We are already struggling to get progress/work in existing IGs that have more specific focus, such as the Media and Entertainment IG or the Web and Networks IG.
1. At the minimum, the charter should be clarified that it's not replacing the current work of the W3C Strategy team
1. the Strategy Lead should not be one of the co-chairs but a participant
1. All of the topics mentioned in scope could be brought to the existing AB-led sessions by the Strategy team and the members. The Strategy team should keep improving its communication during those sessions.

**Comment by fantasai** [comment]
Hi plh,

- Wrt 1 & 2, as long as there's interest in trying, I think it makes sense to try. Not every effort needs to be guaranteed to succeed for it to be worth trying!
- Wrt 3, I believe the intention is to augment the work of the strategy team and improve collaboration between the Team and the Membership in this area. It's hard to see what the problem with the charter is here, you'll need to be more specific about what phrasing is objectionable.
- What's the motivation for not co-chairing the group? Is it lack of time, or perception of conflicts, or...?
- These are not mutually exclusive. The AB-led sessions are very open-ended, both in terms of topics and participation; it's good for getting vague general feedback, but not really for focused effort on anything, which this IG proposal enables.

**Comment by michaelchampion** [comment]
> We are already struggling to get progress/work in existing IGs that have more specific focus, such as the Media and Entertainment IG or the Web and Networks IG.

That's a very interesting bit of information.  As I understood from following discussion of this proposal in the AB repo, the original proposal for a CG morphed into a proposal for an IG for various reasons, especially the difference between the CG and IG IPR policies.  If the AB  had been aware that existing IGs are "struggling", that might have led to a different AB suggestion for how to proceed with @dennis-dingwei 's initiative.  


> All of the topics mentioned in scope could be brought to the existing AB-led sessions 

As I recall, the idea for this CG or IG came out of AB-led sessions; a number of participants wished that W3C had some mechanism to analyze industry trends (such as the excitement a few years ago about blockchains / "web3" and the current excitement about generative AI) and report on them to members trying understand them and their likely impact on the web.  That's the problem this proposal is trying to address, it would be helpful if the Strategy Team had more concrete advice than to simply have unstructured discussion in the monthly AB-led meetings. 

 The Team itself  *could* lead that kind of analysis, discussion,  and reporting, but has not done so in the past, or at least since TimBL started to disengage 10-15 years ago.   I suppose the AB should now re-consider the underlying problem, assess what W3C could potentially do (defer to the Strategy Team ... form a CG to incubate the work, with a tightly scoped charter that might not scare the corporate lawyers?... double down on the IG proposal ?... or try to fix the Process / IPR issues that constrain CGs trying to do something other than spec incubation.

**Comment by chrisn** [comment]
As a chair of one of those IGs, I understand the concern (happy do discuss separately, if there's interest). But I don't think the CG / IG distinction is a large factor in whether this particular group will be successful. Like any IG it needs engagement from the community. I agree mostly with @fantasai's points - it's worth trying and it should complement the Team's own work, but I don't think someone from the Team necessarily needs to chair it, e.g., if people in the AB are willing.

**Comment by plehegar** [comment]
> * Wrt 1 & 2, as long as there's interest in trying, I think it makes sense to try. Not every effort needs to be guaranteed to succeed for it to be worth trying!
> 

> Wrt 1 & 2, as long as there's interest in trying, I think it makes sense to try. Not every effort needs to be guaranteed to succeed for it to be worth trying!

I do believe there is interest if we manage to find the right Chairs for this Group.

> * Wrt 3, I believe the intention is to augment the work of the strategy team and improve collaboration between the Team and the Membership in this area. It's hard to see what the problem with the charter is here, you'll need to be more specific about what phrasing is objectionable.

I concur with the intention but also had to explain the intention to the Strategy team. It's probably a simple fix in the 'Motivation and Background' to clarify this intention.


> * What's the motivation for not co-chairing the group? Is it lack of time, or perception of conflicts, or...?

Lack of time and enabling the Strategy lead to participate freely in the IG without needing to wear a Chair hat.

> * These are not mutually exclusive. The AB-led sessions are very open-ended, both in terms of topics and participation; it's good for getting vague general feedback, but not really for focused effort on anything, which this IG proposal enables.

Understood.

Fyi, I asked @wareid to add this on the agenda of the upcoming AB-led sessions.

**Comment by dennis-dingwei** [comment]
> > * Wrt 3, I believe the intention is to augment the work of the strategy team and improve collaboration between the Team and the Membership in this area. It's hard to see what the problem with the charter is here, you'll need to be more specific about what phrasing is objectionable.
> 
> I concur with the intention but also had to explain the intention to the Strategy team. It's probably a simple fix in the 'Motivation and Background' to clarify this intention.

Yes, it is intended to design as not overlapping but complementary to the Strategy Team work, at least in the first two stages of the funnel. Is it possible that Strategy Team could help contributing to the 'Motivation and Background' session for their satisfaction?

**Comment by plehegar** [comment]
from AB-led session: CGs should be encouraged to bring their proposals to the IG.

**Comment by plehegar** [comment]
I sent a PR to help address comments. See https://github.com/w3c/charter-drafts/pull/625

**Comment by dennis-dingwei** [comment]
**Mission**

The mission of the Exploration Interest Group is to provide W3C Members with a forum to explore and discuss emerging web-related technology trends and consider how the community could collaborate to shape those trends for the benefit of web users.

**Motivation and Background**

The W3C Process indicates that a role of the Advisory Board is to provide strategic guidance to the W3C. Analogous to Process Document management, the Advisory Board recognized that there is interest among the broader Membership for these discussions and encouraged the creation of a dedicated Interest Group for ongoing strategic conversations.

The goal is to provide a platform to help W3C (including the W3C team) investigating emerging technology trends, analyzing their impacts on the evolution of Web technologies, and proposing ways for W3C to collaborate shaping the trends for the benefit of the Web users.

**Scope**

* Monitor industry and technology trends and analyze their potential impact on the Web.

* Based on these findings, develop strategic narratives to help the W3C community understand these trends, the relevance of W3C activities, or a gap analysis where there are no current W3C activities.

* Provide a forum for members of the W3C community (including the W3C team) to share updates with the Membership as part of broader strategic discussions (e.g., Strategy Team's Incubation Pipeline updates, liaison updates, Community Group updates). This is intended to complement other venues for updates, including both Member-focused discussions (e.g., AC meeting or AB-led Member meeting) and broader community discussions (e.g., TPAC breakouts). The value proposition of this Interest Group is to support deeper ongoing strategic conversations.

* Provide a forum for members of the W3C community (including the W3C team) to seek in-depth strategic input from the W3C Membership. Examples of who might seek strategic guidance from the Interest Group: Community Groups considering transitioning to a Working Group; parties who seek help resolving strategic issues related to a charter in development (as opposed to issues for which another group such as the TAG would be more appropriate).

**Deliverables**

Reports about industry and technology trends, their potential impact on the Web, and how W3C might play a role in shaping their trajectory. 

These reports would be informative only and could be reviewed by the W3C community, and where there appears to be consensus, published as Interest Group Notes.

**Success Criteria**

Reports published by the IG inform strategic conversations within W3C, leading to visible activities such as new Community Groups, improvements or greater consensus around draft Working Group charters, W3C Workshops, AC meeting agenda items, TPAC breakout sessions, structured email discussions within the broader Membership, and productive liaisons.

**Comment by wareid** [comment]
RESOLVED: The AB recommends to go ahead with the charter refinement process for the Exploration IG using the text from: https://github.com/w3c/strategy/issues/451#issuecomment-2520551409

**Comment by plehegar** [comment]
Team is looking for chairs and a team contact.

**Comment by plehegar** [comment]
Next step: find co-chairs and start AC Review by end of February 2025.

**Comment by plehegar** [comment]
This issue still needs to be addressed https://github.com/w3c/charter-drafts/issues/630

**Comment by xueyuanjia** [comment]
AC Review started 2025-03-07.

**Comment by plehegar** [comment]
[Proposed W3C Charter: Exploration Interest Group (until 2025-04-04/05)](https://lists.w3.org/Archives/Public/public-new-work/2025Mar/0000.html)

**Comment by plehegar** [comment]
[Announced](https://lists.w3.org/Archives/Member/w3c-ac-members/2025AprJun/0020.html)
